EnterpriseGatewayPortal.Web/Controllers/UsageReportsController.cs
using EnterpriseGatewayPortal.Core.Domain.Services;
using EnterpriseGatewayPortal.Web.Attribute;
using EnterpriseGatewayPortal.Web.Constants;
using EnterpriseGatewayPortal.Web.Enums;
using EnterpriseGatewayPortal.Web.ViewModel.UsageReports;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseGatewayPortal.Web.Controllers
{
    [ServiceFilter(typeof(SessionValidationAttribute))]
    [Authorize]
    public class UsageReportsController : BaseController
    {
        private readonly ILogger<UsageReportsController> _logger;
        private readonly IUsageReportsService _usageReportsService;
        public UsageReportsController(IAdminLogService adminLogService, IUsageReportsService usageReportsService, ILogger<UsageReportsController> logger) : base(adminLogService)
        {
            _logger = logger;
            _usageReportsService = usageReportsService;

        }
        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new OrganizationUsageReportUsageViewModel();
            return View(viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(OrganizationUsageReportUsageViewModel viewModel)
        {
            string logMessage;
            var organizationUid = (HttpContext.User.Claims.FirstOrDefault(c => c.Type == "OrganizationUid").Value);
            var organizationUsageReports = await _usageReportsService.GetOrganizationUsageReports(organizationUid, viewModel.Year);

            if (organizationUsageReports == null)
            {

                logMessage = $"Failed to get Usage Reports.";
                SendAdminLog(ModuleNameConstants.Payments, ServiceNameConstants.Payments,
                    "Get Organization Usage Reports", LogMessageType.FAILURE.ToString(), logMessage, UUID, Email);

                return NotFound();
            }

            logMessage = $"Successfully received Usage Reports.";
            SendAdminLog(ModuleNameConstants.Payments, ServiceNameConstants.Payments,
                "Get Organization Usage Reports", LogMessageType.FAILURE.ToString(), logMessage, UUID, Email);

            viewModel.OrgUsageReports = new List<OrgUsageReportsViewModel>();
            foreach (var report in organizationUsageReports)
            {
                var model = new OrgUsageReportsViewModel()
                {
                    Id = report.Id,
                    OrgName = OrganizationName,
                    OrganizationId = report.OrganizationId,
                    ReportMonth = report.ReportMonth,
                    ReportYear = report.ReportYear,
                    CreatedOn = report.CreatedOn,
                    TotalInvoiceAmount = report.TotalInvoiceAmount,
                };

                viewModel.OrgUsageReports.Add(model);
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<string> DownloadUsageReport(int reportId)
        {
            return await _usageReportsService.DownloadUsageReport(reportId);
        }

        [HttpGet]
        public async Task<JsonResult> DownloadCurrentMonthOrganizationUsageReport()
        {
            var organizationUid = (HttpContext.User.Claims.FirstOrDefault(c => c.Type == "OrganizationUid").Value);
            var orgName = OrganizationName;
            var currentDate = DateTime.Now;
            var currentMonth = currentDate.Month;
            var currentYear = currentDate.Year;
            var orgNameWithDate = OrganizationName + '_' + currentYear + '-' + currentMonth;

            var response = await _usageReportsService.DownloadCurrentMonthUsageReport(organizationUid);
            if (response.Success)
            {
                return Json(new { Status = response.Success, Message = response.Message, Result = response.Resource, Organization_Name = orgNameWithDate });
            }
            else
            {
                return Json(new { Status = response.Success, Message = response.Message, Result = string.Empty });
            }
        }

    }
}

EnterpriseGatewayPortal.Web/Views/UsageReports/Index.cshtml
@model EnterpriseGatewayPortal.Web.ViewModel.UsageReports.OrganizationUsageReportUsageViewModel
@using EnterpriseGatewayPortal.Web.Models

@{
    ViewBag.Breadcrumb = new List<BreadCrumbModel>
    {
        new BreadCrumbModel { Title = "Payments - Usage Reports", Url = "", IconKey="payments-UsageReports" },
    }; 
}


@{
    ViewData["Title"] = "Payments";
}

<style>
    .updateLink:hover {
        color: blue;
        text-decoration: underline;
    }

    #note {
        padding-right: 10px;
        display: flex;
        justify-content: flex-end;
        padding-bottom: 15px;
    }

    .classshide {
        display: none !important;
    }

    /* ----------- Select dropdown css -------------*/

    .select2-container {
        width: 100% !important;
    }

        .select2-container .select2-selection--single {
            border-radius: 8px;
            align-items: center;
            box-sizing: border-box;
            justify-content: center;
            height: 40px !important;
            border: 1px solid #E2E8F0 !IMPORTANT;
            color: #3E4046 !important;
        }

    .selection {
        width: 100% !important;
    }

    .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #3E4046 !important;
        font-size: 14px;
        font-family: inherit;
        padding: 5px 10px;
    }


    /* Remove default arrow */
    .select2-container--default .select2-selection--single .select2-selection__arrow b {
        border: none !important; /* removes default triangle */
    }

    /* Add your custom arrow */
    .select2-container--default .select2-selection--single .select2-selection__arrow {
        // background: url('@Url.Content("~/assets/images/dropDown-icon-brown.svg")');
        background: url("data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M27.0613 13.0612L17.0613 23.0612C16.9219 23.2011 16.7563 23.312 16.574 23.3877C16.3917 23.4634 16.1962 23.5024 15.9988 23.5024C15.8013 23.5024 15.6059 23.4634 15.4235 23.3877C15.2412 23.312 15.0756 23.2011 14.9363 23.0612L4.93626 13.0612C4.65446 12.7794 4.49615 12.3972 4.49615 11.9987C4.49615 11.6002 4.65446 11.218 4.93626 10.9362C5.21805 10.6544 5.60024 10.4961 5.99876 10.4961C6.39727 10.4961 6.77946 10.6544 7.06126 10.9362L16 19.875L24.9388 10.935C25.2205 10.6532 25.6027 10.4949 26.0013 10.4949C26.3998 10.4949 26.782 10.6532 27.0638 10.935C27.3455 11.2168 27.5039 11.599 27.5039 11.9975C27.5039 12.396 27.3455 12.7782 27.0638 13.06L27.0613 13.0612Z' fill='%2392722A'/%3E%3C/svg%3E");
        //background: url('@Url.Content("~/assets/images/imgDropDownBrown.png")');
        background-repeat: no-repeat;
        background-size: 16px 16px;
        width: 19px;
        top: 11px;
        vertical-align: middle;
        height: 100%;
    }

    .select2-search__field {
        display: none !important;
    }

    // .select2-search select2-search--dropdown {
        // display: none !important;
        //
    }

    .select2-container .select2-dropdown.select2-dropdown--below {
        top: -5px !important;
    }

    .select2-container .select2-search.select2-search--dropdown {
        padding: 0 !important;
    }

</style>

@{
    await Html.RenderPartialAsync("_AlertBox");
}

<div class="classshide">
    <div id='viewer'></div>
</div>
<label class="sub-label">Usage Reports</label>
<div class="row">
    <div class="col-md-12 plr">
        <div class="card" style="height:130px;">
            <div class="card-body">
                <form method="post" asp-action="Index">

                    <div class="row p-b-20" style="margin-top:-15px;">

                        <div class="col-md-3 col-sm-3 col-3">

                            <div class="form-group">
                                <label asp-for="Year" class="col-form-label" style="display: inline-block;"></label><span class="text-danger">*</span>
                               
                                <select asp-for="Year" class="form-control select2" id="yearSelect">
                                    <option value="">select</option>
                                </select>
                              
                                <span asp-validation-for="Year" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-5 col-sm-5 col-5">

                            <div class="d-flex flex-row" style="margin-top: 33px;">
                                <button type="submit" class="btn btn-primary uaeid-primary" style="font-size:12px;">Submit</button>
                                &nbsp;&nbsp;
                                <button type="button" id="downloadBtn" class="btn btn-other" onclick="downloadCurrentMonthUsageReport(event)">
                                    Download current month usage
                                </button>
                            </div>

                        </div>

                        <div class="col-md-4 col-sm-4 col-4">
                            <div id="note" style="justify-content:end;">
                                <b>NOTE: </b> (*) Mark fields are mandatory.
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@if (Model.OrgUsageReports != null)
{
    <div id="organizationUsageReportDiv">
        @await Html.PartialAsync("_OrganizationUsageReport", Model.OrgUsageReports)
    </div>
}

@section scripts{
    <script src="~/assets/js/bootstrap3-typeahead.min.js" asp-append-version="true"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
    <script>
    var uid;
        var base64String;
    $(document).ready(function () {

        $('#networkOverlay').hide();
            document.getElementById("navigationNetworkOverlay").style.display = "none";

        $("#Payments > a")
            .attr("aria-expanded", "true")
            .addClass("active");

        $("#Payments")
            .addClass("submenu-active show");

        $("#Payments .submenu")
            .addClass("show");

        $('#Usage-Reports').addClass('active');

            var ddlYears = document.getElementById("yearSelect");
            var currentYear = (new Date()).getFullYear();

            if (ddlYears.options.length === 1 && ddlYears.options[0].value === "") {
                for (var i = 1; i <= 10; i++) {
                    var option = document.createElement("option");
                    option.innerHTML = currentYear;
                    option.value = currentYear;
                    ddlYears.appendChild(option);
                    currentYear--;
                }
            }

            // Set selected value from Model.Year
            var selectedYear = '@Model.Year';
            if (selectedYear) {
                $('#yearSelect').val(selectedYear).trigger('change');
            }

            $('#yearSelect').select2();

        // var BalanceSheetLink = document.getElementById('PaymentsModle').querySelector('.nav-link');
        // BalanceSheetLink.click();
        $('#homeMenu').addClass('breadcrumb-item').append('Payments > Usage Reports');
        $('#mainMenu').removeClass('breadcrumb-item');
        $('#subMenu').removeClass('breadcrumb-item');
          

    });

        // $('#yearSelect').on('click', function () {

        //     var ddlYears = document.getElementById("yearSelect");

        //     //Determine the Current Year.
        //     var currentYear = (new Date()).getFullYear();

        //    if (ddlYears.options.length === 1 && ddlYears.options[0].value === "") {
        //     //Loop and add the Year values to DropDownList.
        //     for (var i = 1; i <= 10; i++) {
        //         var option = document.createElement("option");
        //         option.innerHTML = currentYear;
        //         option.value = currentYear;
        //         ddlYears.appendChild(option);
        //         currentYear--;
        //     }
        //   }
        // });


        function downloadCurrentMonthUsageReport() {
            event.preventDefault();

                $.ajax({
                    url: '@Url.Action("DownloadCurrentMonthOrganizationUsageReport", "UsageReports")',

                    type: "GET",
                    error: ajaxErrorHandler,
                    beforeSend: function () {
                        $('#overlay').show();
                    },
                    complete: function () {
                        $('#overlay').hide();
                    },
                    success: function (data) {
                        if (data.status) {

                            if (data.result == null || data.result == "") {
                            Swal.fire({ icon: 'error', title: "Error", text: data.message });
                            }
                            else {
                            saveByteArrayCurrentMonth(data.organization_Name, data.result);
                            }
                        }
                        else {
                            Swal.fire({ icon: 'error', title: "Error", text: data.message });
                        }
                    }
                });

        }

        function saveByteArrayCurrentMonth(uid, base64String) {
            var myBytes = base64ToArrayBuffer(base64String);
            var blob = new Blob([myBytes], { type: "application/pdf" });
            var link = document.createElement('a');
            link.href = window.URL.createObjectURL(blob);
            let fileName = uid + ".pdf";
            link.download = fileName;
            link.click();

        }

        function saveByteArray(uid, month, yaer, base64String, orgname) {
            var myBytes = base64ToArrayBuffer(base64String);
            var blob = new Blob([myBytes], { type: "application/pdf" });
            var link = document.createElement('a');
            link.href = window.URL.createObjectURL(blob);
            let fileName = orgname + '_' + month + ".pdf";
            link.download = fileName;
            link.click();

        }

        function base64ToArrayBuffer(base64) {
            var binaryString = window.atob(base64);
            var binaryLen = binaryString.length;
            var bytes = new Uint8Array(binaryLen);
            for (var i = 0; i < binaryLen; i++) {
                var ascii = binaryString.charCodeAt(i);
                bytes[i] = ascii;
            }
            return bytes;
        }

    </script>
}

EnterpriseGatewayPortal.Web/Views/UsageReports/_OrganizationUsageReport.cshtml
@*@model IEnumerable<EnterpriseGatewayPortal.Core.DTOs.OrganizationUsageReportDTO>*@
@model IEnumerable<EnterpriseGatewayPortal.Web.ViewModel.UsageReports.OrgUsageReportsViewModel>
@{
    var hasData = Model != null && Model.Count() > 0;
}
<style>
    .classshide {
        display: none !important;
    }

    .table.dataTable.table {
        margin-top: 0 !important;
    }

    .col-sm-12 {
        padding-right: 0px !important;
        padding-left: 0px !important;
    }


    /* ----------- Select dropdown css -------------*/

    .select2-container {
        width: 100% !important;
    }

        .select2-container .select2-selection--single {
            border-radius: 8px;
            align-items: center;
            box-sizing: border-box;
            justify-content: center;
            height: 40px !important;
            border: 1px solid #E2E8F0 !IMPORTANT;
            color: #3E4046 !important;
        }

    .selection {
        width: 100% !important;
    }

    .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #3E4046 !important;
        font-size: 14px;
        font-family: inherit;
        padding: 5px 10px;
    }


    /* Remove default arrow */
    .select2-container--default .select2-selection--single .select2-selection__arrow b {
        border: none !important; /* removes default triangle */
    }

    /* Add your custom arrow */
    .select2-container--default .select2-selection--single .select2-selection__arrow {
        background: url("data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M27.0613 13.0612L17.0613 23.0612C16.9219 23.2011 16.7563 23.312 16.574 23.3877C16.3917 23.4634 16.1962 23.5024 15.9988 23.5024C15.8013 23.5024 15.6059 23.4634 15.4235 23.3877C15.2412 23.312 15.0756 23.2011 14.9363 23.0612L4.93626 13.0612C4.65446 12.7794 4.49615 12.3972 4.49615 11.9987C4.49615 11.6002 4.65446 11.218 4.93626 10.9362C5.21805 10.6544 5.60024 10.4961 5.99876 10.4961C6.39727 10.4961 6.77946 10.6544 7.06126 10.9362L16 19.875L24.9388 10.935C25.2205 10.6532 25.6027 10.4949 26.0013 10.4949C26.3998 10.4949 26.782 10.6532 27.0638 10.935C27.3455 11.2168 27.5039 11.599 27.5039 11.9975C27.5039 12.396 27.3455 12.7782 27.0638 13.06L27.0613 13.0612Z' fill='%2392722A'/%3E%3C/svg%3E");
        background-repeat: no-repeat;
        background-size: 16px 16px;
        width: 19px;
        top: 11px;
        vertical-align: middle;
        height: 100%;
    }

    .select2-search__field {
        display: none !important;
    }


    .select2-container .select2-dropdown.select2-dropdown--below {
        top: -5px !important;
    }

    .select2-container .select2-search.select2-search--dropdown {
        padding: 0 !important;
    }
</style>
@if (Model == null || Model.Count() == 0)
{
    <style>
        table {
            height: 70% !important;
        }

        .table-hover > tbody > tr:hover > td {
            background: none !important;
        }

        body {
            overflow: hidden;
        }

        /* Apply 100% height to all DataTables wrappers */
        .dataTables_wrapper {
            height: 100% !important;
        }

            /* Apply 100% height only to the second .row inside any DataTables wrapper */
            .dataTables_wrapper > .row:nth-of-type(2) {
                height: 100% !important;
            }

        td:not([style*="display: none"]) {
            border-bottom-right-radius: 12px !important;
            border-bottom-left-radius: 12px !important;
        }
    </style>
}
<div class="row">
    <div class="col-md-12 plr">

        <div class=card-body>
            <div class="row align-items-center justify-content-between" style="padding-left: 15px; padding-bottom:15px;">
                <!-- Left: Search bar (will be injected by DataTables) -->
                <div class="col-md-6 col-sm-12 d-flex align-items-center plr" id="custom-search-container"></div>

            </div>

            <table id="UsageReportTable" class="table-striped table-bordered table-hover table-checkable order-column full-width table @(Model == null || Model.Count() == 0 ? "empty-table" : "")">
                <thead>
                    <tr>
                        <th>Month</th>
                        <th>Year</th>
                        <th>Invoice Amount</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model == null || Model.Count() == 0)
                    {
                        <tr>
                            <td style="display: none;"></td>
                            <td style="text-align:center" valign="top" colspan="6" class="dataTables_empty">
                                <img class="NoRecordsCls" src="~/assets/images/No-Records-icon.svg" alt="No records" style=" display:block; margin:0 auto 8px;">
                                <p class="NoRecordFound-paragarph">No records found</p>

                            </td>

                            <td style="display: none;"></td>
                            <td style="display: none;"></td>

                        </tr>
                    }
                    else
                    {
                        @foreach (var item in @Model)
                        {
                            <tr class="odd gradeX">
                                <td>@item.ReportMonth</td>
                                <td>@item.ReportYear</td>
                                <td>@item.TotalInvoiceAmount</td>
                                <td class="valigntop">
                                    <div class="">
                                        <button class="btn btn-xs deepPink-bgcolor no-margin Actions_btn" type="button" data-toggle="dropdown" style="font-size:0.8rem;"
                                                aria-expanded="false">
                                            Actions
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-left" role="menu">
                                            <li>

                                                <a onclick="hello('@item.OrganizationId', '@item.Id', '@item.ReportMonth', '@item.ReportYear', '@item.OrgName')" style="align-items:center;">
                                                    <img src="~/assets/images/FileArrowDown.svg" />
                                                    Download
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>


<script>

    $(document).ready(function () {

        $('#networkOverlay').hide();
        var table = $("#UsageReportTable").DataTable({
            "bLengthChange": false,
            "searching": true,
             "paging": @hasData.ToString().ToLower(),
             "info": @hasData.ToString().ToLower(),
            "initComplete": function () {
                // Move the search bar into our custom container
                $(".dataTables_filter").appendTo("#custom-search-container");
                $('.dataTables_filter input[type="search"]').attr('placeholder', 'Search');
                $('.dataTables_filter label').contents().filter(function () {
                    return this.nodeType === 3;
                }).remove();

            }
        });

    });
    function hello(uid, id, reportMonth, reportYear, name) {

        $.ajax({
            type: "GET",
            url: '@Url.Action("DownloadUsageReport", "UsageReports")',
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            data: { 'reportId': id },
            beforeSend: function () {
                $('#overlay').show();
            },
            complete: function () {
                $('#overlay').hide();
            },
            success: function (data) {
                if (data == null) {
                    Swal.fire({ icon: 'error', title: "Error", text: "Failed to download the report" });
                }
                else {
                    saveByteArray(uid, reportMonth, reportYear, data, name);
                }
            },
            error: ajaxErrorHandler,
            failure: function (response) {
                Swal.fire({ icon: 'error', title: "Error", text: "Failed to process your request" });
            }
        });
    }



    function saveByteArray(uid, month, yaer, base64String, orgname) {
        var myBytes = base64ToArrayBuffer(base64String);
        var blob = new Blob([myBytes], { type: "application/pdf" });
        var link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        //let fileName = uid + ".pdf";
        let fileName = orgname + '_' + month + ".pdf";
        link.download = fileName;
        link.click();
        //var myBytes = base64ToArrayBuffer(bytes);
        //var blob = new Blob([myBytes], { type: "application/pdf" });
        //var link = window.URL.createObjectURL(blob);
        //window.open(link, '', 'height=650,width=840');
    }

    function base64ToArrayBuffer(base64) {
        var binaryString = window.atob(base64);
        var binaryLen = binaryString.length;
        var bytes = new Uint8Array(binaryLen);
        for (var i = 0; i < binaryLen; i++) {
            var ascii = binaryString.charCodeAt(i);
            bytes[i] = ascii;
        }
        return bytes;
    }
</script>